export const DEEP_SYNONYM_CLUSTERS: string[][] = [
  [
    "opportunity",
    "chance",
    "possibility",
    "opening",
    "prospect",
    "occasion",
    "option",
    "avenue",
    "room to grow",
    "potential path",
    "available opening",
    "promising prospect",
    "possible avenue",
    "way forward",
  ],
  [
    "different",
    "distinct",
    "separate",
    "unlike",
    "dissimilar",
    "divergent",
    "contrasting",
    "varied",
    "not the same",
    "nonidentical",
    "discrete",
    "individual",
    "unique",
    "set apart",
    "clearly separate",
    "meaningfully distinct",
    "not alike",
    "not equivalent",
    "non-equivalent",
    "separable",
    "independent",
    "contrary",
    "opposing",
    "alternate",
    "another",
    "other",
    "unshared",
    "unmatched",
    "apart",
    "unconnected",
    "separate in kind",
    "different in nature",
  ],
  [
    "different from",
    "distinct from",
    "separate from",
    "unlike",
    "not the same as",
    "differs from",
    "contrasts with",
    "varies from",
    "stands apart from",
    "is unlike",
    "is distinct from",
    "is separate from",
    "is not identical to",
    "does not equal",
    "is not equivalent to",
    "is set apart from",
    "is meaningfully different from",
    "is clearly separate from",
    "is different in nature from",
    "is different in kind from",
    "is not comparable to",
    "is unlike in character",
    "is separate in meaning from",
    "can be distinguished from",
    "should be distinguished from",
    "is not the same thing as",
    "is not interchangeable with",
    "is not synonymous with",
    "is apart from",
    "is dissimilar to",
  ],
  [
    "high",
    "strong",
    "elevated",
    "substantial",
    "considerable",
    "marked",
    "above-average",
    "great",
    "large",
    "major",
    "significant",
    "heightened",
    "increased",
    "raised",
    "pronounced",
    "intense",
    "powerful",
    "robust",
    "notable",
    "prominent",
    "serious",
    "deep",
    "heavy",
    "rich",
    "full",
    "ample",
    "exceptional",
    "superior",
    "peak",
    "top-tier",
    "sizable",
    "meaningful",
    "solid",
    "well-developed",
    "well-above-average",
  ],
  [
    "self-esteem",
    "self-worth",
    "self-respect",
    "confidence",
    "self-regard",
    "sense of worth",
    "self-confidence",
    "self-belief",
    "self-assurance",
    "personal confidence",
    "inner confidence",
    "self-image",
    "self-value",
    "self-appreciation",
    "self-acceptance",
    "sense of self",
    "personal esteem",
    "self-trust",
    "self-possession",
    "sense of value",
    "sense of self-worth",
    "personal worth",
    "inner assurance",
    "healthy confidence",
    "positive self-regard",
    "stable self-respect",
    "secure self-worth",
    "solid self-confidence",
    "strong self-worth",
    "well-grounded confidence",
    "positive self-image",
    "healthy self-respect",
    "healthy self-esteem",
    "strong self-esteem",
    "positive sense of self",
    "healthy sense of self-worth",
  ],
  [
    "high self-esteem",
    "healthy self-esteem",
    "strong self-worth",
    "strong self-esteem",
    "positive self-regard",
    "healthy confidence",
    "solid self-confidence",
    "secure self-worth",
    "positive self-image",
    "stable self-respect",
    "healthy self-respect",
    "high confidence",
    "robust self-esteem",
    "well-grounded confidence",
    "strong sense of self-worth",
    "healthy sense of self-worth",
    "positive sense of self",
    "healthy self-confidence",
    "secure self-confidence",
    "well-developed self-respect",
    "positive self-worth",
    "grounded self-belief",
    "steady self-assurance",
    "stable confidence",
    "healthy self-regard",
    "solid sense of worth",
    "positive personal confidence",
    "secure sense of self",
    "strong inner confidence",
    "healthy self-image",
    "confident self-regard",
    "healthy personal esteem",
    "stable self-confidence",
    "secure self-regard",
    "strong self-belief",
    "positive inner confidence",
    "well-rooted self-worth",
    "balanced self-esteem",
    "steady self-worth",
    "healthy self-trust",
    "clear sense of worth",
    "grounded confidence",
  ],
  [
    "narcissism",
    "self-absorption",
    "egotism",
    "self-importance",
    "vanity",
    "self-centeredness",
    "egoism",
    "self-obsession",
    "grandiosity",
    "excessive self-focus",
    "self-admiration",
    "self-preoccupation",
    "ego-centeredness",
    "inflated self-view",
    "personal vanity",
    "self-infatuation",
    "self-involvement",
    "ego fixation",
    "self-regard",
    "self-focus",
    "self-love",
    "overblown self-regard",
    "inflated ego",
    "grandiose self-image",
    "self-centered focus",
    "excessive pride",
    "egocentrism",
    "self-importance",
    "ego-driven behavior",
    "self-absorbed thinking",
    "attention-seeking self-focus",
    "inflated sense of self",
    "overconfidence in oneself",
    "excessive self-regard",
    "self-glorification",
    "self-idolization",
    "ego inflation",
    "excessive self-interest",
    "self-centered worldview",
    "grandiose self-regard",
    "inflated self-importance",
    "self-focused vanity",
    "ego preoccupation",
    "self-obsessiveness",
    "excessive ego focus",
    "inflated pride",
  ],
  [
    "narcissistic",
    "self-absorbed",
    "egotistical",
    "self-important",
    "vain",
    "self-centered",
    "ego-driven",
    "self-obsessed",
    "grandiose",
    "overly self-focused",
    "self-admiring",
    "ego-centered",
    "self-preoccupied",
    "self-involved",
    "self-regarding",
    "attention-seeking",
    "self-infatuated",
    "egocentric",
    "self-fixated",
    "overconfident",
    "self-glorifying",
    "inflated",
    "prideful",
    "self-focused",
    "self-absorbing",
    "egoistic",
    "self-serving",
    "grandstanding",
    "status-seeking",
    "admiration-seeking",
    "overly self-important",
    "self-centered in manner",
    "grandiosity-driven",
    "ego-focused",
    "inflated in self-view",
    "self-oriented",
    "excessively self-regarding",
    "overly self-regarding",
    "ego-preoccupied",
    "self-importance driven",
    "focused on admiration",
    "focused on status",
    "self-aggrandizing",
    "self-elevating",
    "overly prideful",
    "centered on the self",
  ],
  [
    "entitlement",
    "privilege",
    "deservingness",
    "special treatment",
    "automatic right",
    "claim",
    "expectation",
    "sense of being owed",
    "assumed privilege",
    "presumed right",
    "special claim",
    "unearned expectation",
    "right to receive",
    "demand for preference",
    "expectation of favor",
    "sense of due",
    "claim to advantage",
    "belief in being owed",
    "assumed right",
    "expected privilege",
    "sense of special rights",
    "claim of privilege",
    "belief in special treatment",
    "expectation of special treatment",
    "presumed advantage",
    "demand for special status",
    "unearned claim",
    "privileged expectation",
    "sense of special claim",
    "belief in deserved preference",
    "belief in being especially owed",
    "expectation of preferential treatment",
    "assumption of special privilege",
    "claim to special status",
    "feeling of being owed more",
    "belief in automatic preference",
    "expectation of extra privilege",
    "presumed special right",
    "sense of deserved advantage",
    "assumption of earned privilege",
    "claim to special consideration",
    "belief in personal entitlement",
    "expectation of priority treatment",
    "sense of owed recognition",
    "assumed claim to preference",
  ],
  [
    "superiority",
    "dominance",
    "greater status",
    "higher standing",
    "advantage",
    "supremacy",
    "upper hand",
    "greater importance",
    "higher rank",
    "elevated status",
    "higher position",
    "better standing",
    "perceived advantage",
    "greater worth",
    "higher value",
    "greater authority",
    "dominant position",
    "higher status",
    "superior standing",
    "higher importance",
    "elevated rank",
    "preferred position",
    "stronger standing",
    "greater power",
    "superior status",
    "higher placement",
    "stronger position",
    "social advantage",
    "rank advantage",
    "sense of being above others",
    "sense of higher standing",
    "belief in being above others",
    "feeling of superiority",
    "assumed higher worth",
    "perceived higher rank",
    "belief in greater status",
    "feeling of elevated importance",
    "sense of greater value",
    "belief in being better",
    "assumed dominance",
    "elevated self-position",
    "claimed higher standing",
    "perceived upper status",
    "sense of greater authority",
    "belief in higher worth",
  ],
  [
    "sense of superiority and entitlement",
    "feeling of being superior and owed special treatment",
    "belief in being above others and deserving special treatment",
    "superiority and entitlement",
    "feeling of higher status and special privilege",
    "belief in greater importance and deserved privilege",
    "superior self-view and entitlement",
    "inflated status and special claim",
    "belief in being better and owed more",
    "superiority complex and entitlement",
    "sense of being above others and owed preference",
    "belief in higher standing and special treatment",
    "feeling of superiority plus entitlement",
    "high-status self-view and assumed privilege",
    "belief in greater worth and special rights",
    "view of oneself as superior and especially deserving",
    "belief in being above others and owed more",
    "inflated self-view plus special claim",
    "assumed superiority and privilege",
    "belief in higher rank and deserved preference",
    "feeling of being better and especially owed",
    "sense of elevated status and entitlement",
    "belief in superior worth and special treatment",
    "grandiose self-view and entitlement",
    "belief in being more important and owed recognition",
    "sense of personal superiority and deserved advantage",
    "inflated status plus assumed privilege",
    "belief in being above others and entitled",
    "feeling of higher worth and special claim",
    "superior self-image and entitlement",
    "belief in greater value and owed preference",
    "sense of higher status and special rights",
    "inflated self-importance and entitlement",
    "belief in being exceptional and owed more",
    "feeling of superiority and deserved privilege",
    "assumed higher worth and special treatment",
    "belief in dominance and special claim",
    "elevated self-view and entitlement",
    "sense of being superior and especially deserving",
    "belief in greater standing and automatic privilege",
    "feeling of higher importance and owed preference",
    "assumed superior status and entitlement",
    "belief in elevated worth and special rights",
    "inflated sense of status and privilege",
    "sense of being above others and specially owed",
  ],
  [
    "because",
    "since",
    "as",
    "given that",
    "due to the fact that",
    "for the reason that",
    "considering that",
    "seeing that",
    "inasmuch as",
    "for",
    "now that",
    "in light of the fact that",
    "on the grounds that",
    "by reason of the fact that",
    "given the fact that",
    "considering the fact that",
    "in view of the fact that",
    "based on the fact that",
    "considering how",
    "given how",
    "seeing as",
    "seeing as how",
    "being that",
    "forasmuch as",
    "in that",
    "because of the fact that",
    "owing to the fact that",
    "as the fact is that",
    "as the case is that",
    "given the case that",
    "considering the case that",
    "on the basis that",
    "with the understanding that",
    "with the fact that",
    "given the reality that",
    "considering the reality that",
    "as it is true that",
    "insofar as",
    "to the extent that",
    "as much as",
    "given as how",
  ],
  [
    "include",
    "includes",
    "contain",
    "contains",
    "involve",
    "involves",
    "cover",
    "covers",
    "feature",
    "features",
    "take in",
    "takes in",
    "encompass",
    "encompasses",
    "account for",
    "accounts for",
    "comprise",
    "comprises",
    "consist of",
    "consists of",
    "incorporate",
    "incorporates",
    "embrace",
    "embraces",
    "bring in",
    "brings in",
    "extend to",
    "extends to",
    "cover the idea of",
    "cover the ideas of",
  ],
  [
    "narcissism includes",
    "narcissism involves",
    "narcissism contains",
    "narcissism is marked by",
    "narcissism can involve",
    "narcissism often includes",
    "narcissism commonly involves",
    "narcissism is associated with",
    "narcissism features",
    "narcissism may include",
    "narcissism tends to involve",
    "narcissism is characterized by",
    "narcissism can be linked with",
    "narcissism encompasses",
    "narcissism can feature",
    "narcissism may involve",
    "narcissism is defined by",
    "narcissism is shaped by",
    "narcissism is connected with",
    "narcissism can include",
    "narcissism often involves",
    "narcissism commonly includes",
    "narcissism is tied to",
    "narcissism is reflected in",
    "narcissism usually involves",
    "narcissism frequently includes",
    "narcissism frequently involves",
    "narcissism is often marked by",
    "narcissism is commonly marked by",
    "narcissism can be characterized by",
    "narcissism is partly defined by",
    "narcissism is often tied to",
    "narcissism is commonly connected with",
    "narcissism can be reflected in",
    "narcissism is often associated with",
    "narcissism commonly features",
    "narcissism may be linked with",
    "narcissism tends to feature",
    "narcissism can center on",
    "narcissism often centers on",
  ],
  [
    "and",
    "plus",
    "as well as",
    "along with",
    "in addition to",
    "together with",
    "not to mention",
    "as well",
    "with",
    "alongside",
    "besides",
    "including",
    "coupled with",
    "combined with",
    "accompanied by",
    "and also",
    "as a companion to",
    "paired with",
    "joined with",
    "in combination with",
    "in tandem with",
    "together alongside",
    "plus also",
    "also with",
    "in company with",
    "side by side with",
    "in conjunction with",
    "in partnership with",
    "together with the addition of",
    "as an addition to",
    "as well together with",
    "including also",
    "and together with",
    "along together with",
    "beside",
    "next to",
    "in union with",
    "linked with",
    "connected with",
    "joined alongside",
    "in addition",
    "as an added part",
    "as another part",
    "together in addition",
    "also including",
    "plus together with",
    "as well in addition",
    "also alongside",
    "together as well",
    "plus alongside",
    "and in addition",
    "as a further part",
    "with that too",
    "with this also",
    "as another addition",
    "as one more part",
  ],
  [
    "person",
    "individual",
    "human",
    "someone",
    "somebody",
    "participant",
    "member",
    "user",
    "reader",
    "learner",
    "student",
    "adult",
    "child",
    "community member",
    "person involved",
    "single person",
    "human being",
    "individual person",
    "private individual",
    "ordinary person",
    "resident",
    "citizen",
    "worker",
    "peer",
    "neighbor",
    "client",
    "customer",
    "patient",
    "employee",
    "community participant",
    "member of the group",
    "person in question",
  ],
  [
    "people",
    "individuals",
    "humans",
    "persons",
    "folks",
    "others",
    "other people",
    "peers",
    "those around them",
    "other individuals",
    "members",
    "participants",
    "users",
    "readers",
    "learners",
    "students",
    "adults",
    "children",
    "everyone",
    "the public",
    "community members",
    "people involved",
    "those involved",
  ],
  [
    "themselves",
    "personally",
    "on their own",
    "for themselves",
    "as individuals",
    "in their own view",
    "by themselves",
    "independently",
    "alone",
    "their own selves",
    "on their own behalf",
    "for their own part",
    "from their perspective",
    "in their own minds",
    "each personally",
    "each on their own",
    "among themselves",
    "as people",
    "as themselves",
    "within themselves",
    "for their own sake",
    "in their own right",
    "in themselves",
    "through their own efforts",
    "using their own judgment",
    "from their own standpoint",
    "in their personal view",
    "for their own benefit",
    "for their own needs",
    "as their own people",
    "on a personal level",
    "with their own perspective",
    "in their own experience",
    "through their own lens",
    "for their own reasons",
    "in their private view",
    "according to themselves",
    "as their own selves",
    "by their own standards",
    "in their own estimation",
    "for their own selves",
  ],
  [
    "good",
    "positive",
    "healthy",
    "sound",
    "beneficial",
    "constructive",
    "favorable",
    "helpful",
    "useful",
    "valuable",
    "worthwhile",
    "effective",
    "strong",
    "solid",
    "healthy",
    "promising",
    "advantageous",
    "productive",
    "reliable",
    "suitable",
    "appropriate",
    "well-suited",
    "desirable",
    "encouraging",
    "supportive",
    "practical",
    "meaningful",
    "soundly positive",
    "well-grounded",
    "positive in nature",
    "emotionally healthy",
    "solidly positive",
    "genuinely healthy",
    "constructive overall",
    "sound and healthy",
    "self-supportive",
    "affirming",
    "reassuring",
    "stable",
    "well-balanced",
    "healthy-minded",
    "good for them",
    "beneficial overall",
    "personally positive",
    "confidence-building",
    "self-affirming",
    "well-adjusted",
    "wholesome",
  ],
  [
    "easier to read",
    "more readable",
    "easier to understand",
    "clearer to read",
    "simpler to read",
    "clearer for readers",
    "more accessible",
    "easier for readers",
    "simpler to understand",
    "clearer to understand",
    "more reader-friendly",
    "easier to follow",
    "clearer to follow",
    "simpler to follow",
    "more understandable",
    "plain to read",
    "easy to follow",
    "clear and readable",
    "more digestible",
    "more legible",
    "reader-friendly",
    "more accessible to readers",
    "easier to process",
    "clearer in wording",
    "simpler in wording",
    "more straightforward to read",
    "more straightforward",
    "clearer overall",
    "simpler overall",
    "easier to take in",
    "easier to grasp",
    "clearer to grasp",
    "simpler to grasp",
    "more easily understood",
    "easier to comprehend",
    "clearer to comprehend",
    "simpler to comprehend",
    "more readable overall",
    "easier for people to read",
    "clearer for people to read",
    "simple to read",
    "straightforward to read",
    "clearer and simpler",
    "plain and readable",
  ],
  [
    "better",
    "improved",
    "stronger",
    "clearer",
    "more useful",
    "more effective",
    "enhanced",
    "refined",
    "upgraded",
    "more polished",
    "more capable",
    "more helpful",
    "more accurate",
    "more natural",
    "more precise",
    "more readable",
    "more fluent",
    "more efficient",
    "more suitable",
    "more reliable",
    "more complete",
    "higher quality",
    "more advanced",
    "more developed",
    "more sophisticated",
    "more robust",
    "more useful overall",
    "better developed",
    "superior",
    "greater",
    "higher",
    "more capable",
    "more worthy",
    "stronger overall",
    "more convincing",
    "more successful",
    "more fitting",
    "more appropriate",
    "more effective overall",
    "better suited",
    "better aligned",
    "more accomplished",
    "more advanced overall",
    "better formed",
  ],
  [
    "similar",
    "alike",
    "comparable",
    "related",
    "much the same",
    "parallel",
    "close",
    "resembling",
    "akin",
    "analogous",
    "near",
    "matching",
    "equivalent",
    "corresponding",
    "like",
    "shared",
    "connected",
    "kindred",
    "comparable in nature",
    "close in meaning",
    "broadly alike",
    "roughly equivalent",
    "of a kind",
    "in the same family",
    "close together",
    "comparable overall",
    "similar in nature",
    "alike in character",
    "much alike",
    "nearly alike",
    "closely related",
    "broadly comparable",
    "in the same category",
    "of the same type",
    "not far apart",
    "parallel in meaning",
    "connected in kind",
    "corresponding in nature",
    "sharing qualities",
    "having similarities",
    "similar overall",
  ],
  [
    "view",
    "see",
    "regard",
    "consider",
    "perceive",
    "interpret",
    "understand",
    "look at",
    "take",
    "read",
    "judge",
    "assess",
    "frame",
    "treat",
    "think of",
    "think about",
    "look on",
    "make sense of",
    "characterize",
    "conceptualize",
    "evaluate",
    "appraise",
    "recognize",
    "observe",
    "perspective",
    "outlook",
    "opinion",
    "viewpoint",
    "point of view",
    "way of seeing",
    "interpretation",
    "perception",
    "stance",
    "angle",
    "lens",
    "self-view",
    "self-perception",
    "attitude",
    "belief",
    "frame of reference",
    "personal view",
    "sense of self",
    "understanding of oneself",
  ],
  [
    "status",
    "standing",
    "rank",
    "position",
    "prestige",
    "social standing",
    "reputation",
    "placement",
    "station",
    "level",
    "role",
    "importance",
    "standing in the group",
    "social position",
    "relative position",
    "recognized rank",
    "public standing",
    "social prestige",
    "ranked position",
    "standing among others",
  ],
  [
    "relationship",
    "relationships",
    "connection",
    "connections",
    "bond",
    "bonds",
    "relation",
    "relations",
    "personal tie",
    "personal ties",
    "association",
    "associations",
    "partnership",
    "partnerships",
    "social link",
    "social links",
    "interaction",
    "interactions",
    "rapport",
    "affiliation",
    "attachment",
    "social bond",
    "human connection",
    "personal connection",
  ],
  [
    "work",
    "working",
    "function",
    "operate",
    "perform",
    "labor",
    "collaborate",
    "cooperate",
    "team",
    "interact",
    "coordinate",
    "partner",
    "contribute",
    "serve",
    "run",
    "act",
    "carry out tasks",
    "do the job",
    "produce results",
    "work together",
    "operate effectively",
    "function well",
    "coordinate efforts",
    "join forces",
    "act together",
    "work jointly",
    "share effort",
    "perform together",
    "contribute jointly",
    "engage together",
    "cooperate closely",
    "collaborate effectively",
  ],
  [
    "work with",
    "collaborate with",
    "cooperate with",
    "team with",
    "interact with",
    "coordinate with",
    "partner with",
    "join with",
    "engage with",
    "work alongside",
    "operate with",
    "share work with",
    "work together with",
    "join forces with",
    "coordinate efforts with",
    "collaborate alongside",
    "cooperate alongside",
    "team up with",
    "connect with",
    "coordinate alongside",
    "participate with",
    "contribute with",
    "act together with",
    "perform alongside",
    "engage alongside",
    "work in partnership with",
    "collaborate in partnership with",
    "cooperate in partnership with",
    "work jointly with",
    "coordinate jointly with",
    "partner alongside",
    "collaborate closely with",
    "cooperate closely with",
    "work side by side with",
    "share effort with",
    "combine efforts with",
    "work in tandem with",
    "team alongside",
    "coordinate in tandem with",
    "collaborate in tandem with",
  ],
  [
    "caring",
    "kind",
    "considerate",
    "compassionate",
    "supportive",
    "thoughtful",
    "empathetic",
    "warm",
    "gentle",
    "helpful",
    "concerned",
    "understanding",
    "attentive",
    "nurturing",
    "protective",
    "sympathetic",
    "humane",
    "patient",
    "generous",
    "responsive",
    "emotionally supportive",
  ],
  [
    "important",
    "key",
    "useful",
    "meaningful",
    "essential",
    "crucial",
    "vital",
    "significant",
    "central",
    "major",
    "critical",
    "valuable",
    "necessary",
    "relevant",
    "notable",
    "worthwhile",
    "consequential",
    "weighty",
    "high-priority",
    "core",
    "foundational",
    "substantial",
    "serious",
    "material",
  ],
  [
    "difficult",
    "challenging",
    "hard",
    "complex",
    "demanding",
    "tough",
    "tricky",
    "arduous",
    "hard to understand",
    "not easy",
    "complicated",
    "involved",
    "advanced",
    "demanding to understand",
    "hard to grasp",
    "hard to follow",
    "not straightforward",
    "less straightforward",
    "more complex",
    "mentally demanding",
    "cognitively demanding",
    "harder to process",
    "harder to learn",
    "harder to explain",
    "difficult to understand",
    "difficult to follow",
    "difficult to grasp",
    "challenging to understand",
    "challenging to follow",
    "challenging to grasp",
    "conceptually hard",
    "conceptually challenging",
    "somewhat complex",
    "more demanding",
    "less simple",
    "less clear",
    "not simple",
    "harder",
    "more challenging",
    "more involved",
    "more complicated",
    "more advanced",
  ],
  [
    "tool",
    "utility",
    "application",
    "app",
    "software",
    "instrument",
    "assistant",
    "helper",
    "system",
    "platform",
    "program",
    "resource",
    "aid",
    "feature",
    "workflow aid",
    "writing aid",
    "local utility",
    "offline utility",
    "editing tool",
    "writing tool",
    "software tool",
    "local app",
    "offline app",
    "helper app",
    "text tool",
    "language tool",
    "paraphrasing tool",
    "rewrite tool",
    "editing utility",
    "writing assistant",
    "text assistant",
    "local assistant",
    "drafting aid",
    "revision aid",
    "wording aid",
    "phrase tool",
    "wording tool",
    "sentence tool",
    "text utility",
    "rewrite assistant",
    "paraphrase assistant",
  ],
  [
    "use",
    "used",
    "utilize",
    "employ",
    "apply",
    "leverage",
    "make use of",
    "put to use",
    "draw on",
    "rely on",
    "turn to",
    "work with",
    "operate",
    "handle",
    "deploy",
    "adopt",
    "bring in",
    "take advantage of",
    "practice",
    "implement",
    "exercise",
    "make practical use of",
  ],
  [
    "show",
    "display",
    "present",
    "indicate",
    "make clear",
    "reveal",
    "demonstrate",
    "exhibit",
    "show clearly",
    "make visible",
    "bring up",
    "surface",
    "highlight",
    "point out",
    "signal",
    "communicate",
    "express",
    "convey",
    "illustrate",
    "explain",
    "make apparent",
    "make evident",
    "make plain",
    "call attention to",
    "draw attention to",
    "set out",
    "lay out",
    "present clearly",
    "display clearly",
    "show the status of",
    "show the progress of",
    "indicate clearly",
    "visibly show",
    "visually display",
    "bring into view",
    "make easy to see",
    "make progress visible",
    "show what is happening",
    "display what is happening",
    "present the state of",
  ],
  [
    "slow",
    "sluggish",
    "delayed",
    "unresponsive",
    "laggy",
    "slow-moving",
    "leisurely",
    "gradual",
    "unhurried",
    "slow to respond",
    "slow to load",
    "slow to update",
    "not responsive",
    "less responsive",
    "taking time",
    "taking too long",
    "dragging",
    "draggy",
    "delayed-feeling",
    "low-speed",
    "not fast",
    "less fast",
    "slower",
    "slower than expected",
    "lagging",
    "slow-feeling",
    "choppy",
    "stuttering",
    "hesitant",
    "late",
    "behind",
    "not quick",
    "slow in response",
    "slow in the interface",
    "slow in practice",
    "slow overall",
    "performance-limited",
    "not immediate",
    "taking longer",
    "delayed in response",
    "slow responding",
    "laggy overall",
    "slow overall in use",
    "delayed overall",
    "not snappy",
  ],
  [
    "useful",
    "helpful",
    "valuable",
    "practical",
    "worthwhile",
    "effective",
    "beneficial",
    "usable",
    "productive",
    "constructive",
    "worth using",
    "of use",
    "useful in practice",
    "helpful in practice",
    "practically helpful",
    "genuinely helpful",
    "actionable",
    "serviceable",
    "worth having",
    "good to have",
    "advantageous",
    "supportive",
    "meaningful",
    "relevant",
    "valuable to use",
    "helpful to use",
    "useful overall",
    "effective overall",
    "practical overall",
    "helpful overall",
    "useful for the task",
    "helpful for the task",
    "valuable for the task",
    "effective for the task",
    "practical for the task",
    "supportive for the task",
    "useful as an option",
    "helpful as an option",
    "valuable as an option",
    "effective as an option",
  ],
  [
    "improve",
    "boost",
    "increase",
    "enhance",
    "strengthen",
    "raise",
    "refine",
    "upgrade",
    "better",
    "make better",
    "make stronger",
    "make clearer",
    "make more useful",
    "make more effective",
    "make more natural",
    "make more precise",
    "make more readable",
    "make more fluent",
    "build up",
    "advance",
    "develop",
    "raise the quality of",
    "lift",
    "sharpen",
    "polish",
    "fine-tune",
    "strengthen overall",
    "improve overall",
    "boost overall",
    "improve quality",
    "boost quality",
    "increase quality",
    "improve energy",
    "boost energy",
    "increase energy",
    "raise energy",
    "support energy",
    "help energy",
    "make energy better",
    "make energy stronger",
    "make something better",
  ],
  [
    "give",
    "offer",
    "provide",
    "share",
    "supply",
    "present",
    "deliver",
    "hand over",
    "pass along",
    "make available",
    "extend",
    "grant",
    "furnish",
    "send",
    "contribute",
    "provide access to",
    "offer up",
    "give out",
    "hand",
    "issue",
    "serve",
    "make possible",
    "make an option available",
    "offer an option",
    "provide an option",
    "share an option",
    "give a choice",
    "offer a choice",
    "provide a choice",
    "give support",
    "offer support",
    "provide support",
    "give help",
    "offer help",
    "provide help",
    "give information",
    "offer information",
    "provide information",
    "give guidance",
    "offer guidance",
  ],
  [
    "problem",
    "issue",
    "concern",
    "difficulty",
    "obstacle",
    "challenge",
    "trouble",
    "complication",
    "pain point",
    "matter",
    "sticking point",
    "source of trouble",
    "point of friction",
    "roadblock",
    "barrier",
    "setback",
    "fault",
    "defect",
    "bug",
    "error",
    "support issue",
    "customer issue",
    "user issue",
    "reported issue",
    "reported problem",
    "underlying issue",
    "main issue",
    "central issue",
    "core problem",
    "practical problem",
    "technical problem",
    "customer concern",
    "user concern",
    "service concern",
    "difficulty being reported",
    "issue being reported",
    "problem being reported",
    "thing going wrong",
    "thing to fix",
    "thing to address",
  ],
  [
    "quickly",
    "rapidly",
    "fast",
    "swiftly",
    "speedily",
    "promptly",
    "at speed",
    "in little time",
    "without delay",
    "right away",
    "soon",
    "rapidly enough",
    "very quickly",
    "more quickly",
    "fairly quickly",
    "quite quickly",
    "in a short time",
    "in a brief time",
    "at a fast pace",
    "at a quick pace",
    "with speed",
    "at once",
    "immediately",
    "in short order",
    "before long",
    "quickly overall",
    "rapidly overall",
    "at a rapid pace",
    "at a brisk pace",
    "briskly",
    "soon enough",
    "without much delay",
    "with little delay",
    "in moments",
    "over little time",
    "in less time",
    "fast enough",
    "quickly enough",
    "in a timely way",
    "in timely fashion",
    "in quick time",
    "in rapid time",
    "quickly in practice",
    "rapidly in practice",
    "with quick timing",
  ],
  [
    "make",
    "makes",
    "create",
    "creates",
    "produce",
    "produces",
    "construct",
    "constructs",
    "build",
    "builds",
    "form",
    "forms",
    "generate",
    "generates",
    "develop",
    "develops",
    "craft",
    "crafts",
    "assemble",
    "assembles",
    "shape",
    "shapes",
    "bring about",
    "brings about",
  ],
  [
    "need",
    "require",
    "call for",
    "depend on",
    "want",
    "seek",
    "necessitate",
    "demand",
    "have to have",
    "be in need of",
    "be required to have",
    "benefit from",
    "be helped by",
    "look for",
    "ask for",
    "rely on",
    "stand in need of",
    "have a need for",
    "be missing",
    "be short of",
    "be lacking",
    "require access to",
    "call for more",
    "seek out",
    "use",
    "want more",
    "be helped with",
    "depend upon",
    "have reason to seek",
    "be likely to require",
    "be likely to seek",
    "be expected to require",
    "be expected to seek",
    "be in want of",
    "be served by",
    "be aided by",
    "be supported by",
    "be addressed by",
    "be satisfied by",
    "be met by",
    "be served through",
    "be improved by",
    "be assisted by",
    "have cause to seek",
    "have reason to require",
  ],
  [
    "may",
    "might",
    "could",
    "can",
    "is likely to",
    "has the potential to",
    "may possibly",
    "might possibly",
    "could potentially",
    "is able to",
    "has a chance to",
    "may well",
    "might well",
    "can sometimes",
    "may sometimes",
    "could sometimes",
    "is capable of",
    "has room to",
    "can potentially",
    "might be able to",
    "could be able to",
    "may be able to",
    "has the capacity to",
    "can be expected to",
    "could be expected to",
    "may be expected to",
    "might be expected to",
    "can tend to",
    "may tend to",
    "could tend to",
    "might tend to",
    "has some chance to",
    "has some potential to",
    "can plausibly",
    "may plausibly",
    "could plausibly",
    "might plausibly",
    "can reasonably",
    "may reasonably",
    "could reasonably",
    "might reasonably",
    "can in some cases",
    "may in some cases",
    "could in some cases",
    "might in some cases",
  ],
  [
    "but",
    "however",
    "yet",
    "though",
    "although",
    "nevertheless",
    "nonetheless",
    "still",
    "even so",
    "all the same",
    "on the other hand",
    "by contrast",
    "in contrast",
    "despite that",
    "even then",
    "rather",
    "instead",
    "whereas",
    "while",
    "except",
    "only",
    "just",
    "still though",
    "however still",
    "yet still",
    "even though",
    "despite this",
    "despite that fact",
    "at the same time",
    "with that said",
    "that said",
    "even so though",
    "in spite of that",
    "on the contrary",
    "contrastingly",
    "notwithstanding",
    "regardless",
    "even with that",
    "though still",
    "while still",
    "despite everything",
    "even so still",
    "still however",
    "yet even so",
    "while nevertheless",
  ],
  [
    "yourself",
    "oneself",
    "you personally",
    "your own self",
    "yourself as a person",
    "your own identity",
    "your own person",
    "yourself individually",
    "who you are",
    "your inner self",
    "your personal self",
    "your individual self",
    "your own being",
    "your own perspective",
    "your own sense of self",
    "your own self-worth",
    "your personal identity",
    "your self-image",
    "your self-view",
    "your self-perception",
    "your own character",
    "your own value",
    "your own standing",
    "your own worth",
    "your own confidence",
    "your inner identity",
    "your sense of identity",
    "yourself personally",
    "the person you are",
    "your own individuality",
    "your personal worth",
    "your private self",
    "your inward self",
    "your core self",
    "your own self-image",
    "your own self-perception",
    "your individual identity",
    "your personal sense of self",
    "your own sense of worth",
    "yourself in your own view",
    "your own inner identity",
    "your personal self-image",
    "your own personal worth",
    "your own understanding of yourself",
    "your individual sense of self",
  ],
];
